
Output demo.gif
Set FontSize 25
Set Width 1600
Set Height 900 
Set Shell zsh


Type "./dukit --help"
Enter
Sleep 1.5s

Type "./dukit"
Sleep 1s
Enter
Sleep 1.5s

Type "./dukit -b"
Sleep 1s
Enter
Sleep 1s

Type "./dukit -i"
Sleep 1s
Enter
Sleep 1s
Type "11jlrx"
Escape
Sleep 1s 
Type ":wq"
Sleep 500ms 
Enter

Sleep 1s 
Type "./dukit -f"
Sleep 1s 
Enter
Sleep 1s 
Escape
Escape

Type "./dukit -k"
Sleep 1s 
Enter
Sleep 1s
Type "a"
Sleep 1s
Type "d"
Sleep 1s
Enter
Sleep 2s

